version: '3.8'

services:
  postgres:
    image: postgres
    environment:
      - POSTGRES_DB=my_store
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
    ports:
      - 5432:5432
    volumes:
      - ./postgres_data:/var/lib/postgresql@14/data:rw

  pgadmin:
    image: dpage/pgadmin4:latest
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=admin
    ports:
      - 5050:80

  # mariadb:
  #   image: mariadb
  #   restart: always
  #   environment:
  #     - MARIADB_ROOT_PASSWORD=admin123
  #     - MARIADB_DATABASE=my_store
  #   ports:
  #     - 3307:3306
  #   volumes:
  #     - ./mariadb_data:/var/lib/mysql
  # mysql:
  #   image: mysql:5.7
  #   restart: always
  #   environment:
  #     - MYSQL_DATABASE=my_store
  #     #- MYSQL_ALLOW_EMPTY_PASSWORD
  #     #- MYSQL_USER=root
  #     - MYSQL_ROOT_PASSWORD=admin123
  #     - MYSQL_PORT=3306
  #   ports:
  #     # <Port exposed> : <MySQL Port running inside container>
  #     - 3306:3306
  #   expose:
  #     # Opens port 3306 on the container
  #     - '3306'
  #   volumes:
  #     - ./mysql_data:/var/lib/mysql

  # phpmyadmin:
  #   image: phpmyadmin/phpmyadmin
  #   environment:
  #     - MYSQL_ROOT_PASSWORD=admin123
  #     - PMA_HOST=mysql
  #   ports:
  #     - 8080:80
